In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
data = {
    "sepal_length": [
        5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,
        5.4,4.8,4.8,4.3,5.8,5.7,5.4,5.1,5.7,5.1,
        5.4,5.1,4.6,5.1,4.8,5.0,5.0,5.2,5.2,4.7,
        4.8,5.4,5.2,5.5,4.9,5.0,5.5,4.9,4.4,5.1,
        5.0,4.5,4.4,5.0,5.1,4.8,5.1,4.6,5.3,5.0,
        
        7.0,6.4,6.9,5.5,6.5,5.7,6.3,4.9,6.6,5.2,
        5.0,5.9,6.0,6.1,5.6,6.7,5.6,5.8,6.2,5.6,
        5.9,6.1,6.3,6.1,6.4,6.6,6.8,6.7,6.0,5.7,
        5.5,5.5,5.8,6.0,5.4,6.0,6.7,6.3,5.6,5.5,
        5.5,6.1,5.8,5.0,5.6,5.7,5.7,6.2,5.1,5.7,
        
        6.3,5.8,7.1,6.3,6.5,7.6,4.9,7.3,6.7,7.2,
        6.5,6.4,6.8,5.7,5.8,6.4,6.5,7.7,7.7,6.0,
        6.9,5.6,7.7,6.3,6.7,7.2,6.2,6.1,6.4,7.2,
        7.4,7.9,6.4,6.3,6.1,7.7,6.3,6.4,6.0,6.9,
        6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
    ],

    "sepal_width": [
        3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,
        3.7,3.4,3.0,3.0,4.0,4.4,3.9,3.5,3.8,3.8,
        3.4,3.7,3.6,3.3,3.4,3.0,3.4,3.5,3.4,3.2,
        3.1,3.4,4.1,4.2,3.1,3.2,3.5,3.6,3.0,3.4,
        3.5,2.3,3.2,3.5,3.8,3.0,3.8,3.2,3.7,3.3,
        
        3.2,3.2,3.1,2.3,2.8,2.8,3.3,2.4,2.9,2.7,
        2.0,3.0,2.2,2.9,2.9,3.1,3.0,2.7,2.2,2.5,
        3.2,2.8,2.5,2.8,2.9,3.0,2.8,3.0,2.9,2.6,
        2.4,2.4,2.7,2.7,3.0,3.4,3.1,2.3,3.0,2.5,
        2.6,3.0,2.6,2.3,2.7,3.0,2.9,2.9,2.5,2.8,
        
        3.3,2.7,3.0,2.9,3.0,3.0,2.5,2.9,2.5,3.6,
        3.2,2.7,3.0,2.5,2.8,3.0,2.9,2.6,2.8,2.2,
        3.2,2.8,2.8,2.7,3.3,3.2,2.8,3.0,2.8,3.0,
        2.8,3.8,2.8,2.8,2.6,3.0,3.4,3.1,3.0,3.1,
        3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
    ],

    "petal_length": [
        1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,
        1.5,1.6,1.4,1.1,1.2,1.5,1.3,1.4,1.7,1.5,
        1.7,1.5,1.0,1.7,1.9,1.6,1.6,1.5,1.4,1.6,
        1.6,1.5,1.5,1.4,1.5,1.2,1.3,1.4,1.3,1.5,
        1.3,1.3,1.3,1.6,1.9,1.4,1.6,1.4,1.5,1.4,
        
        4.7,4.5,4.9,4.0,4.6,4.5,4.7,3.3,4.6,3.9,
        3.5,4.2,4.0,4.7,3.6,4.4,4.5,4.1,4.5,3.9,
        4.8,4.0,4.9,4.7,4.3,4.4,4.8,5.0,4.5,3.5,
        3.8,3.7,3.9,5.1,4.5,4.5,4.7,4.4,4.1,4.0,
        4.4,4.6,4.0,3.3,4.2,4.2,4.2,4.3,3.0,4.1,
        
        6.0,5.1,5.9,5.6,5.8,6.6,4.5,6.3,5.8,6.1,
        5.1,5.3,5.5,5.0,5.1,5.3,5.5,6.7,6.9,5.0,
        5.7,4.9,6.7,4.9,5.7,6.0,4.8,4.9,5.6,5.8,
        6.1,6.4,5.6,5.1,5.6,6.1,5.6,5.5,4.8,5.4,
        5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
    ],

    "petal_width": [
        0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,
        0.2,0.2,0.1,0.1,0.2,0.4,0.4,0.3,0.3,0.3,
        0.2,0.4,0.2,0.5,0.2,0.2,0.4,0.2,0.2,0.2,
        0.2,0.4,0.1,0.2,0.2,0.2,0.2,0.1,0.2,0.2,
        0.3,0.3,0.2,0.6,0.4,0.3,0.3,0.2,0.2,0.2,
        
        1.4,1.5,1.5,1.3,1.5,1.3,1.6,1.0,1.3,1.4,
        1.0,1.5,1.0,1.4,1.3,1.4,1.5,1.0,1.5,1.1,
        1.8,1.3,1.5,1.2,1.3,1.4,1.4,1.7,1.5,1.0,
        1.1,1.0,1.2,1.6,1.5,1.6,1.5,1.3,1.3,1.3,
        1.2,1.4,1.2,1.0,1.3,1.2,1.3,1.3,1.1,1.3,
        
        2.5,1.9,2.1,1.8,2.2,2.1,1.7,1.8,1.8,1.8,
        2.0,1.9,2.1,2.0,2.4,2.3,1.8,2.2,2.3,1.5,
        2.3,2.0,2.0,1.8,2.1,1.8,1.8,1.8,2.1,1.6,
        1.9,2.0,2.2,1.5,1.4,2.3,2.4,1.8,1.8,2.1,
        2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
    ],

    "species": [
        "setosa"
    ] * 50 + [
        "versicolor"
    ] * 50 + [
        "virginica"
    ] * 50
}

df = pd.DataFrame(data)
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [3]:
df.describe(include="all")

,sepal_length,sepal_width,petal_length,petal_width,species
count,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,setosa
freq,NaN,NaN,NaN,NaN,50
mean,5.843333,3.048667,3.758000,1.195333,NaN
std,0.828066,0.432060,1.765298,0.755502,NaN
min,4.300000,2.000000,1.000000,0.100000,NaN
25%,5.100000,2.800000,1.600000,0.300000,NaN
50%,5.800000,3.000000,4.350000,1.300000,NaN
75%,6.400000,3.300000,5.100000,1.800000,NaN


In [4]:
X = df.drop("species", axis=1)
y = df["species"]

In [5]:
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [6]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
#ساخت مدل
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Actual:", y_test)
print("Predicted:", y_pred)

Actual: [0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 1 1 0 2 0]
Predicted: [0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]


In [32]:
#ارزیابی ها
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9666666666666667


In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [34]:
#سوال:کدام پیش بینی اشتباه پیش بینی شده.جواب بخش دوم
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [35]:
from sklearn.metrics import roc_auc_score
y_prob = model.predict_proba(X_test)

print(y_prob)
roc_auc = roc_auc_score(
    y_test,
    y_prob,
    multi_class="ovr"
)

print("ROC-AUC:", roc_auc)

[[9.85259020e-01 1.47409373e-02 4.32378317e-08]
 [1.37998475e-03 3.89693224e-01 6.08926791e-01]
 [1.87342624e-01 8.08608153e-01 4.04922297e-03]
 [1.56190791e-01 8.39736297e-01 4.07291153e-03]
 [9.88215908e-01 1.17840585e-02 3.31746584e-08]
 [4.39785722e-03 6.87184240e-01 3.08417903e-01]
 [9.95130580e-01 4.86941523e-03 5.03551171e-09]
 [9.38671816e-01 6.13278940e-02 2.90480915e-07]
 [1.98777597e-04 1.69497721e-01 8.30303502e-01]
 [1.36513976e-02 7.36186126e-01 2.50162476e-01]
 [1.09403644e-06 2.56269730e-02 9.74371933e-01]
 [1.33141554e-04 1.30762379e-01 8.69104479e-01]
 [7.08775718e-06 2.28452456e-02 9.77147667e-01]
 [6.69823596e-03 8.32608805e-01 1.60692959e-01]
 [9.73036358e-01 2.69635507e-02 9.15300876e-08]
 [9.75611555e-01 2.43883808e-02 6.44134732e-08]
 [9.83149568e-01 1.68504177e-02 1.47202298e-08]
 [3.14023047e-02 9.47124499e-01 2.14731964e-02]
 [3.92496989e-03 7.56915706e-01 2.39159324e-01]
 [2.16346267e-03 4.42455922e-01 5.55380615e-01]
 [9.70729471e-01 2.92704536e-02 7.574165

In [36]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    X_train,
    y_train,
    cv=6,
    scoring="accuracy"
)

print(scores)

[0.9  1.   0.95 0.9  1.   1.  ]


In [37]:
param_grid = {
    "C": [0.01, 0.1, 1, 10, 100]
}

grid = GridSearchCV(
    LogisticRegression(max_iter=1000),
    param_grid,
    cv=5,
    scoring="accuracy"
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Accuracy:", grid.best_score_)

Best Parameters: {'C': 1}
Best CV Accuracy: 0.9666666666666668


In [38]:
best_model = grid.best_estimator_

print(best_model)

LogisticRegression(C=1, max_iter=1000)


In [39]:
y_pred_best = best_model.predict(X_test)

print(y_pred_best)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]


In [40]:


final_accuracy = accuracy_score(y_test, y_pred_best)

print("Final Test Accuracy:", final_accuracy)

Final Test Accuracy: 0.9666666666666667


In [41]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    random_state=42
)

model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

Accuracy: 0.9333333333333333


In [42]:

param_grid2 = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 3, 5, 10],
}

grid2= GridSearchCV(
    model_rf,
    param_grid2,
    cv=5,
    scoring="accuracy"
)

grid2.fit(X_train, y_train)

print("Best Parameters:", grid2.best_params_)
print("Best CV Accuracy:", grid2.best_score_)

Best Parameters: {'max_depth': 3, 'n_estimators': 50}
Best CV Accuracy: 0.9583333333333334


In [43]:
best_model2 = grid2.best_estimator_

y_pred2 = best_model2.predict(X_test)

print(y_pred2)
print(accuracy_score(y_test, y_pred2))

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]
0.9666666666666667


In [44]:
gm= confusion_matrix(y_test, y_pred2)

print(cm)

[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

param_grid3 = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 0.2],
    "max_depth": [2, 3, 5]
}

grid3 = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid=param_grid3,
    cv=5,
    scoring="accuracy"
)

grid3.fit(X_train, y_train)

print("Best Parameters:", grid3.best_params_)
print("Best CV Accuracy:", grid3.best_score_)

In [ ]:
best_model3 = grid3.best_estimator_

y_pred3 = best_model3.predict(X_test)

print(y_pred3)
print(accuracy_score(y_test, y_pred3))

In [ ]:
tm= confusion_matrix(y_test, y_pred3)

print(tm)

In [ ]:
from sklearn.neural_network import MLPClassifier

param_grid4 = {
    "hidden_layer_sizes": [(10,), (50,), (100,)],
    "activation": ["relu", "tanh"],
    "alpha": [0.0001, 0.001, 0.01],
    "learning_rate_init": [0.001, 0.01]
}

grid4 = GridSearchCV(
    MLPClassifier(
        random_state=42,
        max_iter=1000
    ),
    param_grid4 ,
    cv=5,
    scoring="accuracy"
)

grid4.fit(X_train, y_train)

print("Best Parameters:", grid4.best_params_)
print("Best CV Accuracy:", grid4.best_score_)

In [ ]:
best_model4 = grid4.best_estimator_

y_pred4 = best_model4.predict(X_test)

print(y_pred4)
print("Final Test Accuracy:", accuracy_score(y_test, y_pred4))

In [ ]:
def predict_zanbagh(sepal_length, sepal_width, petal_length, petal_width):
    new_flower = [[
        sepal_length,
        sepal_width,
        petal_length,
        petal_width
    ]]
    
    
    new_scaled = scaler.transform(new_flower)
    
    prediction = best_model4.predict(new_scaled)
    
    species = encoder.classes_[prediction[0]]
    
    probabilities = best_model4.predict_proba(new_scaled)[0]
    
    print("Predicted species:", species)
    print("Probabilities:", probabilities)

In [ ]:
predict_zanbagh(5.1, 3.5, 1.4, 0.2)